variables:
  - &node_image "node:18"
  - &buildx_image "woodpeckerci/plugin-docker-buildx"
  - &platforms "linux/amd64"

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

steps:
  Generate version file:
    image: alpine/git
    commands:
      - git describe --always --tags > version

  Install Backend Dependencies:
    image: *node_image
    commands:
      - cd backend
      - npm install
      - cd ..

  Install Frontend Dependencies:
    image: *node_image
    commands:
      - cd frontend
      - npm install
      - cd ..

  Test Backend:
    image: *node_image
    environment:
      SESSION_SECRET: 64ee54e91d5ea65c2fff46f7bf0d6b2c
      DB_NAME: camphouse
      DB_HOST: mongodb
      DB_PORT: "27017"
      DB_USER: admin
      DB_PASS: password
      JWT_SECRET: bff572ca273261b7bd0cb4a2f201913e
    commands:
      - cd backend
      - npm test
      - cd ..

  Test Frontend:
    image: *node_image
    commands:
      - cd frontend
      - npm run test:unit
      - cd ..

  Lint Backend:
    image: *node_image
    commands:
      - cd backend
      - npm run lint
      - cd ..

  Lint Frontend:
    image: *node_image
    commands:
      - cd frontend
      - npm run lint
      - cd ..

  Deploy to Docker Hub:
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/camphouse
      dockerfile: Dockerfile
      platforms: *platforms
      tag: latest
    when:
      event: push

  Deploy Tagged Version:
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/camphouse
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG#v}"]
    when:
      event: tag

  Deploy Pull Request:
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/camphouse
      dockerfile: Dockerfile
      platforms: *platforms
      tag: pull_${CI_COMMIT_PULL_REQUEST}
    when:
      event: pull_request
