when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &node_image "node:18"
  - &buildx_image "woodpeckerci/plugin-docker-buildx"
  - &platforms "linux/amd64"

steps:
  Deploy to CapRover:
    image: *node_image
    secrets: [caprover_password, caprover_url, caprover_name]
    commands:
      - npm install -g caprover
      - caprover login
      - caprover deploy -n caprover -a camphouse -b main
    when:
      event: [push, tag]
      branch: ${CI_REPO_DEFAULT_BRANCH}

  Deploy to Docker Hub:
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/camphouse
      dockerfile: Dockerfile
      platforms: *platforms
      tag: latest
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  Deploy Tagged Version:
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/camphouse
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG#v}"]
    when:
      event: tag
      branch: ${CI_REPO_DEFAULT_BRANCH}

  Deploy Pull Request:
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/camphouse
      dockerfile: Dockerfile
      platforms: *platforms
      tag: pull_${CI_COMMIT_PULL_REQUEST}
    when:
      event: pull_request

depends_on:
  - test
